// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByt3A847gfxoZaiGg4jEB9eFJ7PXGE0Uo',
    appId: '1:475849675976:web:b67d5d3a2147ed27cb41fd',
    messagingSenderId: '475849675976',
    projectId: 'presportal-f9049',
    authDomain: 'presportal-f9049.firebaseapp.com',
    storageBucket: 'presportal-f9049.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ5_K_YsozJczrprt83y9GsKTm7I61r20',
    appId: '1:475849675976:android:69458428265ec0d8cb41fd',
    messagingSenderId: '475849675976',
    projectId: 'presportal-f9049',
    storageBucket: 'presportal-f9049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdTBHTvg6fyXC_i1FjsYOis4-YB2DwSzM',
    appId: '1:475849675976:ios:d6b1e7de0cc6d2a1cb41fd',
    messagingSenderId: '475849675976',
    projectId: 'presportal-f9049',
    storageBucket: 'presportal-f9049.firebasestorage.app',
    iosBundleId: 'com.example.projectwmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdTBHTvg6fyXC_i1FjsYOis4-YB2DwSzM',
    appId: '1:475849675976:ios:d6b1e7de0cc6d2a1cb41fd',
    messagingSenderId: '475849675976',
    projectId: 'presportal-f9049',
    storageBucket: 'presportal-f9049.firebasestorage.app',
    iosBundleId: 'com.example.projectwmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByt3A847gfxoZaiGg4jEB9eFJ7PXGE0Uo',
    appId: '1:475849675976:web:27edff877fa54402cb41fd',
    messagingSenderId: '475849675976',
    projectId: 'presportal-f9049',
    authDomain: 'presportal-f9049.firebaseapp.com',
    storageBucket: 'presportal-f9049.firebasestorage.app',
  );
}
